seo:
  site_name: Melissa Studio
  title: Web devoloper & Design
  description: |-
    Need to upgrade your business ? Get a a website that look good and convert. 
    Custom build website, Design, Branding.
  keywords: website, Webdeveloper, designer
  social_image:
  author: Melissa Mija
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: '#4A4444'
  light-text_color: '#FAF6F0'
  featured-text_color: '#767964'
  featured-text-white_color: white
  bg-dark_color: '#767964'
  bg-light_color: '#FAF6F0'
