seo:
  site_name: Melissa Studio
  title: Web devoloper & Design
  description: >
    Mélissa Studio is a creative studio where you can get a custom website,
    shopify e-commerce, branding and design for your business. 

    We also specialized in social media management. 
  keywords: website, Webdeveloper, designer
  social_image:
  author: Melissa Mija
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark-text_color: '#4a4444'
  light-text_color: '#faf6f0'
  featured-text_color: '#767964'
  featured-text-white_color: '#ffffff'
  bg-dark_color: '#767964'
  bg-light_color: '#faf6f0'
